//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thinktecture.IdentityServer.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public Entity()
        {
            this.EntityToUser = new HashSet<EntityToUser>();
            this.RoleToEntity = new HashSet<RoleToEntity>();
            this.User = new HashSet<User>();
        }
    
        public System.Guid EntityId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public long NationalRegister { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ActivityId { get; set; }
        public Nullable<long> Code { get; set; }
        public bool IsPerson { get; set; }
        public bool IsHeadOffice { get; set; }
        public bool IsDriver { get; set; }
        public string Nickname { get; set; }
        public short Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public short MaritalStatus { get; set; }
        public string IdNumber { get; set; }
        public string IdExpeditor { get; set; }
        public Nullable<System.DateTime> IdDate { get; set; }
        public bool IsPoliticallyExposed { get; set; }
        public decimal Patrimony { get; set; }
        public bool IsUnreportedIncome { get; set; }
        public bool IsUnreportedActivityOrOccupation { get; set; }
        public bool IsUnreportedPartner { get; set; }
        public decimal MonthlyIncome { get; set; }
        public decimal YearlyIncome { get; set; }
        public Nullable<System.Guid> AddressId { get; set; }
        public Nullable<System.Guid> TelephoneId { get; set; }
        public Nullable<System.Guid> EmailId { get; set; }
    
        public virtual ICollection<EntityToUser> EntityToUser { get; set; }
        public virtual ICollection<RoleToEntity> RoleToEntity { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
