//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thinktecture.IdentityServer.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityToUser
    {
        public System.Guid UserId { get; set; }
        public System.Guid EntityId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual User User { get; set; }
    }
}
