//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thinktecture.IdentityServer.Custom
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.EntityToUser = new HashSet<EntityToUser>();
        }
    
        public System.Guid UserId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UserPrincipalName { get; set; }
        public short Status { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mail { get; set; }
        public Nullable<System.Guid> EntityId { get; set; }
        public Nullable<System.Guid> ResetPasswordToken { get; set; }
        public Nullable<System.DateTime> ResetPasswordSentAt { get; set; }
        public Nullable<System.Guid> ConfirmationToken { get; set; }
        public Nullable<System.DateTime> ConfirmationSentAt { get; set; }
        public Nullable<System.DateTime> ConfirmedAt { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsMaster { get; set; }
        public Nullable<System.Guid> AuthenticationToken { get; set; }
        public int SignInCount { get; set; }
        public Nullable<System.DateTime> CurrentSignInAt { get; set; }
        public string CurrentSignInIp { get; set; }
        public Nullable<System.DateTime> LastSignInAt { get; set; }
        public string LastSignInIp { get; set; }
        public int FailedAttempts { get; set; }
        public Nullable<System.Guid> UnlockToken { get; set; }
        public Nullable<System.DateTime> LockedAt { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual ICollection<EntityToUser> EntityToUser { get; set; }
    }
}
